# Generated by Django 5.2.6 on 2026-01-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='internet_shop.cart'),
            preserve_default=False,
        ),
    ]
