# Generated by Django 5.2.6 on 2026-01-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0003_remove_cart_cart_item_cart_is_active_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
